In [3]:
import numpy as np

In [7]:
x = np.array(["a",40,50,77,88])
print(x)
print(type(x))
print(x.dtype)

['a' '40' '50' '77' '88']
<class 'numpy.ndarray'>
<U11


In [21]:
a2 = np.array([80,40],[40,50])
print(a2)
print(type(a2))
print(a2.shape)

TypeError: Field elements must be 2- or 3-tuples, got '40'

In [23]:
c = np.arange(3,20)
print(c)
type(c)

[ 3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]


numpy.ndarray

In [25]:
a1 = np.array([[3,4,5,8],[4,8,9, np.NaN]])
print(a1)
a1.dtype

[[ 3.  4.  5.  8.]
 [ 4.  8.  9. nan]]


dtype('float64')

In [ ]:
array([ 3, 4, 5],
      [ 7, 2, 8],
      [ 9, 1, 6],
      [10, 9, 18])
print([1:3],[)