In [1]:
import pandas as pd

In [9]:
data = [10,20,30,'a',40]
Series = pd.Series(data)
print(Series)

0    10
1    20
2    30
3     a
4    40
dtype: object


In [12]:
data = [1, 2, 3, 4]
i = ['A', 'B', 'C', 'D']
series = pd.Series(data, index=i)
print(series)

A    1
B    2
C    3
D    4
dtype: int64


In [18]:
data = {'a':20, 'b':40}
series = pd.Series(data)
print(series)

a    20
b    40
dtype: int64


In [22]:
series.replace(20,30)

a    30
b    40
dtype: int64

In [30]:
series.drop('a')

b    40
dtype: int64

In [34]:
import numpy as np
data = np.array([100, 200])
series = pd.Series(data, index = (['a', 'b']))
print(series)

a    100
b    200
dtype: int32


In [49]:
data = {'NAME': ['bharath', 'balaji'], 'Age':[19,19], 'Country': ['usa', 'india']}
df = pd.DataFrame(data)
print(series)

a    100
b    200
dtype: int32


In [59]:
import numpy as np
array = np.array([[1,2], [3,4], [5,8]])
print(array)
df = pd.DataFrame(array, columns=['a', 'b'])
print(df)

[[1 2]
 [3 4]
 [5 8]]
   a  b
0  1  2
1  3  4
2  5  8


In [61]:
import numpy as np
array = np.array([[1,2], [3,4], [5,8]])
print(array)
df = pd.DataFrame(array)
print(df)

[[1 2]
 [3 4]
 [5 8]]
   0  1
0  1  2
1  3  4
2  5  8


In [5]:
import pandas as pd
data ={'roll number': [1,2,3,4,5,6], 'Attendance': [33,44,55,88,99,55], 'cgpa':[9.0,9.1,9.3,9.4,9.9,9.4]}
df = pd.DataFrame(data)
print(df)


   roll number  Attendance  cgpa
0            1          33   9.0
1            2          44   9.1
2            3          55   9.3
3            4          88   9.4
4            5          99   9.9
5            6          55   9.4


In [25]:
import pandas as pd
iris_Df = pd.read_csv("C:/Users/jangi/OneDrive/Desktop/training/9e7fdfb8189f0cdf5d73a494e4a6392a-aaecbd14aeaa468cd749528f291aa8a30c2ea09e/iris_dataset.csv")
print(iris_Df)

     sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
0                  5.1               3.5                1.4               0.2   
1                  4.9               3.0                1.4               0.2   
2                  4.7               3.2                1.3               0.2   
3                  4.6               3.1                1.5               0.2   
4                  5.0               3.6                1.4               0.2   
..                 ...               ...                ...               ...   
145                6.7               3.0                5.2               2.3   
146                6.3               2.5                5.0               1.9   
147                6.5               3.0                5.2               2.0   
148                6.2               3.4                5.4               2.3   
149                5.9               3.0                5.1               1.8   

             target  
0    

In [29]:
iris_Df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 5 columns):
 #   Column             Non-Null Count  Dtype  
---  ------             --------------  -----  
 0   sepal length (cm)  150 non-null    float64
 1   sepal width (cm)   150 non-null    float64
 2   petal length (cm)  150 non-null    float64
 3   petal width (cm)   150 non-null    float64
 4   target             150 non-null    object 
dtypes: float64(4), object(1)
memory usage: 6.0+ KB


In [31]:
iris_Df.head()

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
0                5.1               3.5                1.4               0.2   
1                4.9               3.0                1.4               0.2   
2                4.7               3.2                1.3               0.2   
3                4.6               3.1                1.5               0.2   
4                5.0               3.6                1.4               0.2   

        target  
0  Iris-setosa  
1  Iris-setosa  
2  Iris-setosa  
3  Iris-setosa  
4  Iris-setosa

In [33]:
iris_Df.tail()

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
145                6.7               3.0                5.2               2.3   
146                6.3               2.5                5.0               1.9   
147                6.5               3.0                5.2               2.0   
148                6.2               3.4                5.4               2.3   
149                5.9               3.0                5.1               1.8   

             target  
145  Iris-virginica  
146  Iris-virginica  
147  Iris-virginica  
148  Iris-virginica  
149  Iris-virginica

In [37]:
iris_Df.describe()

sepal length (cm)  sepal width (cm)  petal length (cm)  \
count         150.000000        150.000000         150.000000   
mean            5.843333          3.054000           3.758667   
std             0.828066          0.433594           1.764420   
min             4.300000          2.000000           1.000000   
25%             5.100000          2.800000           1.600000   
50%             5.800000          3.000000           4.350000   
75%             6.400000          3.300000           5.100000   
max             7.900000          4.400000           6.900000   

       petal width (cm)  
count        150.000000  
mean           1.198667  
std            0.763161  
min            0.100000  
25%            0.300000  
50%            1.300000  
75%            1.800000  
max            2.500000

In [41]:
import numpy as np
iris_array = np.array(iris_Df)
iris_array

array([[5.1, 3.5, 1.4, 0.2, 'Iris-setosa'],
       [4.9, 3.0, 1.4, 0.2, 'Iris-setosa'],
       [4.7, 3.2, 1.3, 0.2, 'Iris-setosa'],
       [4.6, 3.1, 1.5, 0.2, 'Iris-setosa'],
       [5.0, 3.6, 1.4, 0.2, 'Iris-setosa'],
       [5.4, 3.9, 1.7, 0.4, 'Iris-setosa'],
       [4.6, 3.4, 1.4, 0.3, 'Iris-setosa'],
       [5.0, 3.4, 1.5, 0.2, 'Iris-setosa'],
       [4.4, 2.9, 1.4, 0.2, 'Iris-setosa'],
       [4.9, 3.1, 1.5, 0.1, 'Iris-setosa'],
       [5.4, 3.7, 1.5, 0.2, 'Iris-setosa'],
       [4.8, 3.4, 1.6, 0.2, 'Iris-setosa'],
       [4.8, 3.0, 1.4, 0.1, 'Iris-setosa'],
       [4.3, 3.0, 1.1, 0.1, 'Iris-setosa'],
       [5.8, 4.0, 1.2, 0.2, 'Iris-setosa'],
       [5.7, 4.4, 1.5, 0.4, 'Iris-setosa'],
       [5.4, 3.9, 1.3, 0.4, 'Iris-setosa'],
       [5.1, 3.5, 1.4, 0.3, 'Iris-setosa'],
       [5.7, 3.8, 1.7, 0.3, 'Iris-setosa'],
       [5.1, 3.8, 1.5, 0.3, 'Iris-setosa'],
       [5.4, 3.4, 1.7, 0.2, 'Iris-setosa'],
       [5.1, 3.7, 1.5, 0.4, 'Iris-setosa'],
       [4.6, 3.6, 1.0, 0.2, 'Iri

In [43]:
iris_Df

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
0                  5.1               3.5                1.4               0.2   
1                  4.9               3.0                1.4               0.2   
2                  4.7               3.2                1.3               0.2   
3                  4.6               3.1                1.5               0.2   
4                  5.0               3.6                1.4               0.2   
..                 ...               ...                ...               ...   
145                6.7               3.0                5.2               2.3   
146                6.3               2.5                5.0               1.9   
147                6.5               3.0                5.2               2.0   
148                6.2               3.4                5.4               2.3   
149                5.9               3.0                5.1               1.8   

             target  
0       Iris-setosa  
1       Iris-setosa  
2       Iris-setosa  
3       Iris-setosa  
4       Iris-setosa  
..              ...  
145  Iris-virginica  
146  Iris-virginica  
147  Iris-virginica  
148  Iris-virginica  
149  Iris-virginica  

[150 rows x 5 columns]

In [53]:
iris_Df.iloc[20,3]

0.2

In [59]:
iris_Df.iloc[15:21,[0,3]]

sepal length (cm)  petal width (cm)
15                5.7               0.4
16                5.4               0.4
17                5.1               0.3
18                5.7               0.3
19                5.1               0.3
20                5.4               0.2

In [65]:
iris_Df.iloc[10:20,"sepal.length":"petal.length"]

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
10                5.4               3.7                1.5               0.2   
11                4.8               3.4                1.6               0.2   
12                4.8               3.0                1.4               0.1   
13                4.3               3.0                1.1               0.1   
14                5.8               4.0                1.2               0.2   
15                5.7               4.4                1.5               0.4   
16                5.4               3.9                1.3               0.4   
17                5.1               3.5                1.4               0.3   
18                5.7               3.8                1.7               0.3   
19                5.1               3.8                1.5               0.3   

         target  
10  Iris-setosa  
11  Iris-setosa  
12  Iris-setosa  
13  Iris-setosa  
14  Iris-setosa  
15  Iris-setosa  
16  Iris-setosa  
17  Iris-setosa  
18  Iris-setosa  
19  Iris-setosa